In [5]:
import micropip

await micropip.install('datascience')

In [8]:
import micropip

await micropip.install('numpy')

In [9]:
#Class 3
import numpy as np
#Functions and Tables
import datascience
from datascience import make_array
#Functions - Single argument
def biggest_difference(array_x):
    """Find the biggest difference in absolute value between two adjacent elements"""
    diffs = np.diff(array_x)
    absolute_diffs = abs(diffs)
    return max(absolute_diffs)
    
some_numbers = make_array(2, 4, 5, 6, 4, -1, 1)
big_diff = biggest_difference(some_numbers)
print("The biggest difference is", big_diff)

The biggest difference is 5


 Practice Question 1: Stock Price Fluctuations Scenario: A stock analyst is monitoring the
 daily closing prices of a stock for a week. The prices are as follows:
 150,155,149,160,162,158,165
 Task: Write a function using the given template to calculate the biggest difference (in
 absolute value) between two adjacent closing prices.
     
 Practice Question 2: Temperature Variations Scenario: A weather station records the
 hourly temperatures (in °C) for a single day. The data is as follows:
 25,27,29,26,22,21,23,24
 Task: Using a function similar to biggest_difference, determine the largest temperature
 change between two consecutive hours.

 Practice Question 3: Sales Growth Analysis Scenario: A business owner tracks the monthly
 revenue (in thousands of dollars) for the past 6 months:
 120,125,130,128,132,140
 Task: Create a function to find the largest growth (absolute value) in revenue between
 two consecutive months.
 Output: The maximum revenue growth and the corresponding months.

In [ ]:
#Solution Here






In [ ]:
#Functions - Multiple arguments
def percents(counts, decimal_places):
    """Convert the values in array_x to percents out of the total of array_x."""
    total = counts.sum()
    return np.round((counts/total)*100, decimal_places)
parts = make_array(2, 1, 4)
print("Rounded to 1 decimal place: ", percents(parts, 1))
print("Rounded to 2 decimal places:", percents(parts, 2))
print("Rounded to 3 decimal places:", percents(parts, 3))

In [ ]:
 #default values
def percents(counts, decimal_places=2):
    """Convert the values in array_x to percents out of the total of array_x."""
    total = counts.sum()
    return np.round((counts/total)*100, decimal_places)
parts = make_array(2, 1, 4)
print("Rounded to 1 decimal place:", percents(parts, 1))
print("Rounded to the default number of decimal places:", percents(parts))

In [12]:
from datascience import Table
# Step 1: Create a table with some data
data = Table().with_columns(
    "ID", [1, 2, 3, 4, 5],
    "Value", [10, 20, 30, 40, 50]
)
# Step 2: Define a function to square a number
def square(x):
    return x ** 2
# Step 3: Apply the function to the 'Value' column
data = data.with_column('Squared Value', data.apply(square, 'Value'))
# Step 4: Display the updated table
data.show()

In [ ]:
# Create a table with two columns
data = Table().with_columns(
"Height", [150, 160, 170, 180, 190],
"Weight", [50, 60, 70, 80, 90]
)
# Define a function that calculates BMI
def calculate_bmi(height, weight):
    return weight / (height / 100) ** 2
# Apply the function to both columns
data = data.with_column('BMI', data.apply(calculate_bmi, 'Height', 'Weight'))
# Display the table with the new BMI column
data.show()

 Practice Question 1: Converting Temperatures Scenario: You are given a table containing
 temperatures in Fahrenheit.
 ID Temperature (°F) 1 32 2 50 3 77 4 104 5 212 Task:
 Write a function to convert temperatures from Fahrenheit to Celsius using the formula:
 Celsius=(Fahrenheit−32)× 5/9
 Apply the function to the Temperature column and add a new column Temperature (°C)
 to the table. Display the updated table.
 
 Practice Question 2: Calculating Discounted Prices Scenario: A store has a table of
 products and their original prices.
 ID Price ($) 1 100 2 250 3 400 4 150 5 300 Task:
 Define a function to calculate the discounted price of a product, where the discount rate
 is 20%. Discounted Price=Price×(1−0.2) Apply the function to the Price column and
 create a new column called Discounted Price. Display the updated table.
 
 Practice Question 3: Categorizing Exam Scores Scenario: A teacher has a table of students
 and their scores.
 Student ID Score 1 85 2 67 3 90 4 72 5 60 Task:
 Write a function to categorize scores as "Pass" (if score >= 70) or "Fail" (if score < 70).
 Apply the function to the Score column and add a new column called Result. Display the updated table.

In [ ]:
#Solution Here




In [13]:
#Classifying by One Variable
cones = Table().with_columns(
    'Flavor', make_array('strawberry', 'chocolate',
                         'chocolate', 
                         'strawberry', 'chocolate'),
    'Price', make_array(3.55, 4.75, 6.55, 5.25, 5.25)
)
cones
cones.group('Flavor')

Flavor     | count
chocolate  | 3
strawberry | 2

In [14]:
cones = Table().with_columns(
    'Flavor', make_array('strawberry', 'chocolate',
                         'chocolate', 
                         'strawberry', 'chocolate'),
    'Price', make_array(3.55, 4.75, 6.55, 5.25, 5.25)
)
cones
cones.group('Flavor', sum)

Flavor     | Price sum
chocolate  | 16.55
strawberry | 8.8

In [15]:
#Two Variables: Counting the Number in Each Paired Category
more_cones = Table().with_columns(
    'Flavor', make_array('strawberry', 'chocolate', 
                         'chocolate', 'strawberry', 
                         'chocolate', 'bubblegum'),
    'Color', make_array('pink', 'light brown', 
                        'dark brown', 'pink', 
                        'dark brown', 'pink'),
    'Price', make_array(3.55, 4.75, 5.25, 5.25,
                        5.25, 4.75)
)
more_cones
more_cones.group(['Flavor', 'Color'])

Flavor     | Color       | count
bubblegum  | pink        | 1
chocolate  | dark brown  | 2
chocolate  | light brown | 1
strawberry | pink        | 2

In [16]:
#Two Variables: Counting the Number in Each Paired Category
more_cones = Table().with_columns(
    'Flavor', make_array('strawberry', 'chocolate', 
                         'chocolate', 'strawberry', 
                         'chocolate', 'bubblegum'),
    'Color', make_array('pink', 'light brown', 
                        'dark brown', 'pink', 
                        'dark brown', 'pink'),
    'Price', make_array(3.55, 4.75, 5.25, 5.25,
                        5.25, 4.75)
)
more_cones
more_cones.group(['Flavor', 'Color'], sum)

Flavor     | Color       | Price sum
bubblegum  | pink        | 4.75
chocolate  | dark brown  | 10.5
chocolate  | light brown | 4.75
strawberry | pink        | 8.8

In [17]:
more_cones = Table().with_columns(
    'Flavor', make_array('strawberry', 'chocolate', 
                         'chocolate', 'strawberry', 
                         'chocolate', 'bubblegum'),
    'Color', make_array('pink', 'light brown', 
                        'dark brown', 'pink', 
                        'dark brown', 'pink'),
    'Price', make_array(3.55, 4.75, 5.25, 5.25,
                        5.25, 4.75)
)
more_cones
more_cones.pivot('Flavor', 'Color')

Color       | bubblegum | chocolate | strawberry
dark brown  | 0         | 2         | 0
light brown | 0         | 1         | 0
pink        | 1         | 0         | 2

Case Study 1: Retail Store Sales Analysis Scenario: A retail store sells products across
 various categories (e.g., Electronics, Clothing, Home Goods). The store tracks the sales
data of each product, including the product category, the sale amount, and the region
 where it was sold.
 The store owner wants to analyze:
 Total sales per product category. Total sales for each category by region. A pivot table to
 see the sales distribution by category and region. Data: Here is the sales data for the
 retail store:
 Category Region Sale Amount Electronics North 150 Clothing South 200 Home Goods
 East 100 Electronics West 300 Clothing North 150 Home Goods South 250
 
 Case Study 2: Restaurant Sales Analysis by Dish and Time of Day Scenario: A restaurant
 wants to analyze the sales performance of its dishes during different times of the day.
 The data includes the dish type, the time of day (e.g., Breakfast, Lunch, Dinner), and the
 price of each dish.
 The restaurant owner wants to:
 Calculate the total sales per dish type. Calculate the total sales for each dish type by time
 of day. Create a pivot table to see the sales distribution by dish and time of day. Data:
 Here is the restaurant sales data:
 Dish Time of Day Price ($) Pancakes Breakfast 5.00 Sandwich Lunch 7.50 Pasta Dinner
 12.00 Pancakes Breakfast 5.00 Sandwich Dinner 8.00 Pasta Dinner 12.00
 
 Case Study 3: Employee Hours Worked by Department Scenario: A company tracks the
 number of hours worked each week by employees across different departments. The
 data includes the department, the employee’s name, and the number of hours worked.
 The company HR manager wants to:
 Calculate the total hours worked for each department. Calculate the total hours worked
 by each department for each employee. Create a pivot table to see the breakdown of
 total hours worked by department and employee. Data: Here is the employee hours
 worked data:
 Department Employee Hours Worked HR Alice 40 IT Bob 45 IT Carol 50 Marketing Dave
 35 HR Eve 30 Marketing Frank 40

In [18]:
import datascience
from datascience import make_array
#Joining Tables by Columns
cones = Table().with_columns(
 'Flavor', make_array('strawberry', 'vanilla', 
'chocolate', 'strawberry', 
'chocolate'),
 'Price', make_array(3.55, 4.75, 6.55, 5.25, 5.75)
)
cones
ratings = Table().with_columns(
'Kind', make_array('strawberry', 'chocolate', 
'vanilla'), 'Stars', make_array(2.5, 3.5, 4)
)
ratings
rated = cones.join('Flavor', ratings, 'Kind')
rated

Flavor     | Price | Stars
chocolate  | 6.55  | 3.5
chocolate  | 5.75  | 3.5
strawberry | 3.55  | 2.5
strawberry | 5.25  | 2.5
vanilla    | 4.75  | 4

Question 1: School Subject Grades and Teacher Ratings Scenario: A school tracks the
 grades of students across various subjects and the teacher ratings for each subject. You
 have two tables:
 The first table contains the student grades in each subject. The second table contains the
 teacher ratings for each subject. Your task is to join the two tables by subject to analyze
 the grades and ratings together.
 Data: Student Grades Table:
 Subject Grade Math 85 Science 90 History 88 Math 78 Science 95 Teacher Ratings Table:
 Subject Teacher Rating Math 4.2 Science 3.8 History 4.5 Task: Create the tables for
 student grades and teacher ratings. Join the tables on the Subject column. Display the
 resulting table with both the grades and teacher ratings for each subject.
                                                         
 Question 2: Employee Salaries and Departments Scenario: You have two tables that store
 information about employees in a company. One table contains the employees' salaries,
 and the other contains the departments they belong to. You want to join these tables to
 create a combined table of employees with their respective salaries and departments.
 Data: Employee Salaries Table:
 Employee Salary Alice 60000 Bob 75000 Carol 80000 David 55000 Emma 95000
 Departments Table:
 Employee Department Alice HR Bob IT Carol IT David HR Emma Finance Task: Create the
 tables for employee salaries and departments. Join the two tables on the Employee
 column. Display the resulting table with employees, their salaries, and departments.
       
 Question 3: Product Inventory and Sales Data Scenario: A store tracks its inventory and
 sales data in separate tables. One table contains product inventory (product names and
 quantities available), and the other table contains sales data (products sold and sales
 amounts). You need to join these tables to get a combined view of products with both
 their inventory and sales data.

 Data: Product Inventory Table:
 Product Quantity Widget 100 Gadget 150 Sprocket 50 Widget 80 Gadget 120 Sales Data
 Table:
 Product Sales Amount Widget 5000 Gadget 6000 Sprocket 2000 Task: Create the tables
 for product inventory and sales data. Join the tables on the Product column. Display the
 resulting table with products, their quantities, and sales amounts.

#INTRODUCTION TO NUMPY

In [20]:
#CREATION OF ARRAY
import numpy as np
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [21]:
b = np.array([(1.5,2,3), (4,5,6)],
             dtype = float)
print(b)

[[ 1.5  2.   3. ]
 [ 4.   5.   6. ]]


In [22]:
c = np.array([[(1.5,2,3), (4,5,6)],
              [(3,2,1), (4,5,6)]], 
             dtype = float)
print(c)

[[[ 1.5  2.   3. ]
  [ 4.   5.   6. ]]

 [[ 3.   2.   1. ]
  [ 4.   5.   6. ]]]


In [23]:
# Create a 1D array from lists
list_data = [1, 2, 3, 4, 5]
array_1d = np.array(list_data)
print("1D Array:", array_1d)

1D Array: [1 2 3 4 5]


In [24]:
# Create a 1D array from a tuple
tuple_data = (10, 20, 30, 40)
array_from_tuple = np.array(tuple_data)
print("Array from Tuple:", array_from_tuple)

Array from Tuple: [10 20 30 40]


In [25]:
# Mixed input
mixed_data = [(1, 2), [3, 4]]
mixed_array = np.array(mixed_data)
print("Mixed Array:\n", mixed_array)

Mixed Array:
 [[1 2]
 [3 4]]


In [26]:
list_data = [1, 2, 3, 4, 5]
array_1d = np.array(list_data)
l1 = list_data+2
print(l1)

<class 'TypeError'>: can only concatenate list (not "int") to list

In [27]:
list_data = [1, 2, 3, 4, 5]
array_1d = np.array(list_data)
l1 = array_1d+2
print(l1)

[3 4 5 6 7]


 Case Study 1: Creating a 1D NumPy Array from a List of Temperatures Scenario: You are
 analyzing the temperature data for a city over the span of a week. You need to create a
 1D NumPy array that contains the temperatures (in Celsius) for each day of the week.
 Data: Temperatures (in Celsius) for the week: [22, 24, 19, 25, 23, 21, 20]
 Tasks: Create a 1D NumPy array from the provided temperature data.

 Case Study 2: Creating a 2D NumPy Array for Student Marks Scenario: You are analyzing
 the marks of 5 students in 4 different subjects. You need to create a 2D NumPy array that
 represents the marks of the students across the subjects, and you want to calculate the
 total marks for each student.
 Data: Marks of 5 students in 4 subjects: [ [85, 90, 88, 92], # Student 1 [78, 85, 80, 79], #
 Student 2 [90, 92, 85, 87], # Student 3 [88, 84, 91, 89], # Student 4 [76, 79, 80, 82] #
 Student 5 ]
 Tasks: Create a 2D NumPy array using the marks data.

 Case Study 3: Creating a Multi-dimensional NumPy Array for a Grid of Values Scenario:
 You need to create a multi-dimensional NumPy array representing a 3x3 grid of values,
 where each element is the sum of its row and column indices. This grid will represent a
 simple matrix.
 Tasks: Create a 3x3 multi-dimensional NumPy array.

In [28]:
#Creating Arrays using np functions
# Array of zeros 
zeros = np.zeros((2, 3)) # 2x3 matrix of zeros 
print(zeros)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [29]:
# Array of ones 
ones = np.ones((3, 3)) # 3x3 matrix of ones 
print(ones)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [30]:
# Array of a specific value 
filled = np.full((2, 2), 7) # 2x2 matrix filled with 7 
print(filled)

[[7 7]
 [7 7]]


In [31]:
# Identity matrix 
identity = np.eye(3) # 3x3 identity matrix
print(identity)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [32]:
#Creating array using ranges
# Array from a range of values
arr = np.arange(0, 10, 2)  
print(arr)

[0 2 4 6 8]


In [33]:
# Array with evenly spaced values
arr = np.linspace(0, 1, 5) 
print(arr)

[ 0.    0.25  0.5   0.75  1.  ]


In [34]:
#Creating array using random
# Random values between 0 and 1
random_arr = np.random.rand(3, 3)
print(random_arr)

[[ 0.86600939  0.64180239  0.63796095]
 [ 0.74886649  0.61019679  0.03081193]
 [ 0.29912492  0.85718637  0.90740055]]


In [35]:
# Random integers in a range
random_ints = np.random.randint(1, 10, 
                                (2, 2))
print(random_ints)

[[8 3]
 [8 1]]


 Case Study 1: Simulating a Dice Game Scenario: You are designing a simple dice game. In
 this game, two players each roll a die, and the player with the higher roll wins. If the rolls
 are equal, it's a tie.
 Task:
 Simulate the dice rolls using random.randint() for two players. Each die roll should be a
 random integer between 1 and 6 (inclusive). Compare the results and determine the
 winner, or if the game is a tie.
 
 Case Study 2: Randomly Generating Points for a Simulation Scenario: You are working on
 a simulation where you need to generate random points within a 2D grid, where each
 point represents a particle in a physics simulation. The grid size is 10x10, and the x and y
 coordinates of each point must be between 0 and 10.
 Task:
 Use np.random.rand() to generate random coordinates for 10 particles. Scale the
 generated values so they fit within the range [0, 10].
 
 Case Study 3: Simulating Probability in a Coin Toss Scenario: You are conducting a study
 to simulate a series of coin tosses. Each toss can result in either a "Heads" (1) or "Tails"
 (0). You need to simulate the coin toss for 1000 trials and compute the probability of
 getting "Heads".
 Task:
 Use np.random.rand() to simulate 1000 coin tosses. If the random value is greater than
 0.5, consider it "Heads" (1); otherwise, it will be "Tails" (0). Calculate the probability of
 getting "Heads" by dividing the number of "Heads" by the total number of tosses.

In [ ]:
#Solution